### ISSUE TITLE
Streaming URL?

### ISSUE THREAD

**Issue by aleeherasimiuk** [gmpassos/howler.dart#1]
How can set URL as a source?

![image](https://user-images.githubusercontent.com/43499966/63188594-269c7480-c038-11e9-8079-e64626b533b9.png)

Does not work

**Comment by aleeherasimiuk** [comment]
![image](https://user-images.githubusercontent.com/43499966/63191716-9a8e4b00-c03f-11e9-9d6e-516a92ac4e74.png)
I tryed with another URL and works, Is HTTPS the problem?

**Comment by gmpassos** [comment]
You need to provide some console outputs/errors.

I think that this is a browser issue, that is preventing loading of unsecure files.
