### ISSUE TITLE
Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result:

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [gmpassos/howler.dart#3]
Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result:

flutter/.pub-cache/hosted/pub.dartlang.org/howler-1.0.4/lib/src/howler_base.dart:2014:8

I think just add an parameter to the error function and things are fine

**Comment by gmpassos** [comment]
Fixed. Thanks for the pull request
