### ISSUE TITLE
Unable to `unload` an audio

### ISSUE THREAD

**Issue by jaggernod** [gmpassos/howler.dart#6]
Reproduction steps:
1. Load a single audio
2. Start playing the audio
3. `unload()` the audio

Observed behaviour:
NPE is thrown. Due to the null pointer in the `_releaseHtml5Audio` as `audio._unlocked` is null.

Desired behaviour:
Audio is unloaded and ready to play other tracks

**Comment by gmpassos** [comment]
Can you test with the last version?

If possible, send the error stack trace.

**Comment by jaggernod** [comment]
Thank you very much for the answer but I have switched to another solution so am not able to check.

**Comment by SaadArdati** [comment]
@jaggernod out of curiosity, what is the solution you switched to?

**Comment by jaggernod** [comment]
Just plain `AudioElement` form `html_dart2js` is sufficient.
